baseURL = "https://www.bestlandscapingwebsites.com/"
title = "Best Landscaping Websites"
author = "Renaud Gagné"
copyright = "Copyright © 2024, Supersonic sites; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "paper"

[params]
  color = 'linen'

  twitter = 'SupersonicSites'
  facebook = 'SupersonicSites'
  instagram = 'Supersonic_Sites'

  avatar = 'renaud@supersonicsites.com'
  name = 'Renaud Gagné'
  bio = 'Documenting The Journey'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.disqus]
    shortname = 'bestlandscapingwebsites'

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
